echo "** Creating default DB and users"

mysql -u root -p$MYSQL_ROOT_PASSWORD --execute \
"USE $MYSQL_DATABASE;

CREATE USER IF NOT EXISTS '$MYSQL_GRAFANA_USER' IDENTIFIED BY '$MYSQL_GRAFANA_PASSWORD';
GRANT SELECT ON $MYSQL_DATABASE.* TO '$MYSQL_GRAFANA_USER';

CREATE USER IF NOT EXISTS '$MYSQL_LAZY_BYTE_USER' IDENTIFIED BY '$MYSQL_LAZY_BYTE_PASSWORD';
CREATE USER IF NOT EXISTS '$MYSQL_PEDAL_PAL_USER' IDENTIFIED BY '$MYSQL_PEDAL_PAL_PASSWORD';
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT
  ON $MYSQL_DATABASE.*
  TO '$MYSQL_LAZY_BYTE_USER', '$MYSQL_PEDAL_PAL_USER';"

echo "** Finished creating default DB and users"